# Generated by Django 6.0.2 on 2026-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accreditation_no', models.CharField(max_length=100)),
                ('ulr_prefix', models.CharField(max_length=10)),
                ('accreditation_valid_till', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('accreditation_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ulr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('validation_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
