# Generated by Django 6.0.2 on 2026-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_id", models.IntegerField(unique=True)),
                ("laboratory_name", models.CharField(max_length=255)),
                ("cert_no", models.CharField(max_length=100, unique=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("extend_date", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
