# Generated by Django 6.0.2 on 2026-02-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0002_labmaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labmaster",
            name="lab_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
