# Generated by Codex on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0003_alter_labmaster_lab_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lab",
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(default="PENDING", max_length=30),
        ),
        migrations.AddField(
            model_name="labmaster",
            name="labtype",
            field=models.CharField(default="UNKNOWN", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="labmaster",
            name="cert_no",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="labmaster",
            unique_together={("cert_no", "labtype")},
        ),
    ]
